language: go
go:
  - "1.x"
install: GO111MODULE=on go get ./...
script: GO111MODULE=on go test -v -short -cover -benchtime 10ms -bench . -benchmem ./...

notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
