version: '2.1'

services:
  gandalf:
    build: ../../
    volumes:
      - ../../:/go/src/github.com/Nekroze/Gandalf
      - mmock:/mmock
    working_dir: /go/src/github.com/Nekroze/Gandalf/examples/prototype
    environment:
      GANDALF_COLOUR: 'true'
      GANDALF_MOCK_DEST: '/mmock'
      GANDALF_PROVIDER_HOST: 'mock:8083'
    command: go test -v -bench . -benchmem github.com/Nekroze/Gandalf/examples/prototype

  mock:
    image: jordimartin/mmock
    volumes:
      - mmock:/config
    ports:
      - 8082:8082

volumes:
  mmock:
